# Global settings applied to the whole site.  
# “base” is directory to change to before starting build, and
# “public” is the directory to publish (relative to root of your repo).
# “command” is your build command.

[build]
  base    = "frontend"
  publish = "frontend/dist"
  command = "npm run demo"

# Production context: All deploys to the main
# repository branch will inherit these settings.
#[context.production]
#  command = "make production"
#  [context.production.environment]
#    ACCESS_TOKEN = "super secret"