service: aws-nodejs
provider:
  name: aws
  runtime: nodejs8.10
package:
  exclude:
    - generated/**
    - rest/**
    - swagger/**
    - tests/**
plugins:
  - serverless_framework_swagger_integration
  - serverless-offline
custom:
  swagger_file: api/swagger.yaml
  serverless-offline:
    port: 4000
functions:
  postAccountLogin:
    handler: aws/auth/postAccountLogin.main
    events:
      - http:
          method: post
          path: /account/login
          cors: true
  postAccountRegister:
    handler: aws/auth/postAccountRegister.main
    events:
      - http:
          method: post
          path: /account/register
          cors: true
  postAccountConfirm:
    handler: aws/auth/postAccountConfirm.main
    events:
      - http:
          method: post
          path: /account/confirm
          cors: true
  postAccountForgotPassword:
    handler: aws/auth/postAccountForgotPassword.main
    events:
      - http:
          method: post
          path: /account/forgotPassword
          cors: true
  postAccountConfirmPassword:
    handler: aws/auth/postAccountConfirmPassword.main
    events:
      - http:
          method: post
          path: /account/confirmPassword
          cors: true
  getSites:
    handler: aws/sites/getSites.main
    events:
      - http:
          method: get
          path: /sites
          cors: true
  postSites:
    handler: aws/sites/postSites.main
    events:
      - http:
          method: post
          path: /sites
          cors: true
  getSitesCheckSite:
    handler: aws/sites/getSitesCheckSite.main
    events:
      - http:
          method: get
          path: /sites/checkSite
          cors: true
  getKeywords:
    handler: aws/keywords/getKeywords.main
    events:
      - http:
          method: get
          path: /keywords
          cors: true
  postKeywords:
    handler: aws/keywords/postKeywords.main
    events:
      - http:
          method: post
          path: /keywords
          cors: true
  putKeywordsId:
    handler: aws/keywords/putKeywordsId.main
    events:
      - http:
          method: put
          path: '/keywords/{id}'
          cors: true
  deleteKeywordsId:
    handler: aws/keywords/deleteKeywordsId.main
    events:
      - http:
          method: delete
          path: '/keywords/{id}'
          cors: true
  getKeywordCategory:
    handler: aws/keywordCategory/getKeywordCategory.main
    events:
      - http:
          method: get
          path: /keywordCategory
          cors: true
  postKeywordCategory:
    handler: aws/keywordCategory/postKeywordCategory.main
    events:
      - http:
          method: post
          path: /keywordCategory
          cors: true
  getPages:
    handler: aws/pages/getPages.main
    events:
      - http:
          method: get
          path: /pages
          cors: true
  postPages:
    handler: aws/pages/postPages.main
    events:
      - http:
          method: post
          path: /pages
          cors: true
  getPagesPageId:
    handler: aws/pages/getPagesPageId.main
    events:
      - http:
          method: get
          path: '/pages/{pageId}'
          cors: true
  putPagesPageId:
    handler: aws/pages/putPagesPageId.main
    events:
      - http:
          method: put
          path: '/pages/{pageId}'
          cors: true
  deletePagesPageId:
    handler: aws/pages/deletePagesPageId.main
    events:
      - http:
          method: delete
          path: '/pages/{pageId}'
          cors: true
  getViolations:
    handler: aws/violations/getViolations.main
    events:
      - http:
          method: get
          path: '/violations'
          cors: true
  postViolations:
    handler: aws/violations/postViolations.main
    events:
      - http:
          method: post
          path: /violations
          cors: true
  putViolationsId:
    handler: aws/violations/putViolationsId.main
    events:
      - http:
          method: put
          path: '/violations/{id}'
          cors: true
  deleteViolationsId:
    handler: aws/violations/deleteViolationsId.main
    events:
      - http:
          method: delete
          path: '/violations/{id}'
          cors: true
  getUsers:
    handler: aws/users/getUsers.main
    events:
      - http:
          method: get
          path: /users
          cors: true
  getUsersId:
    handler: aws/users/getUsersId.main
    events:
      - http:
          method: get
          path: '/users/{id}'
          cors: true
