swagger: '2.0'
info:
  $ref: ./info/index.yaml
host: locahost
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Auth
  - name: Users
  - name: Pages
  - name: Keywords
  - name: Sites
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
